name: carpool
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_typeahead: ^4.0.0
  google_maps_webservice: ^0.0.20-nullsafety.5
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  cupertino_icons: ^1.0.6
  flutter_lints: ^3.0.0
  firebase_core: ^2.18.0
  firebase_auth: ^4.8.4
  firebase_database: ^10.0.3
  google_maps_flutter: ^2.0.6
  location: ^4.3.0
  connectivity_plus: ^3.0.3
  flutter_email_sender: ^5.0.3
  cloud_firestore: ^4.7.3
  shared_preferences: ^2.0.6
  geocoding: ^3.0.0
  google_sign_in: ^6.0.0
  flutter_facebook_auth: ^4.3.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_gen: ^5.6.0  # Updated flutter_gen to a compatible version
  intl_utils: ^2.8.7  # Updated intl_utils to the latest version

flutter:
  uses-material-design: true

  assets:
    - assets/images/carpool_logo.png
    - assets/images/home_screen_bottom.png
    - assets/images/google_icon.png
    - assets/images/facebook_icon.png
